### ISSUE TITLE
API-Konventionen einhalten: "/proposal" (hand-coded) vs. "/proposals" (generiert)

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-proposal-service#1]

**Comment by rudolfgrauberger** [comment]
Ich habe CP darauf hingewiesen das der aktuelle Stand in dem GitHub-Repository einmal die Collection in Einzahl und einmal in Mehrzahl existiert. CP meinte, dass sein aktueller Stand (noch nicht in GibHub) überhaupt nichts mehr mit dem Stand zu tun hat. 

Deswegen habe ich gesagt, dass er erst mal das Repository/sein Checkout soweit aufräumen und pushen soll. Danach gucke ich mir das nochmal an ob es noch immer so ist.

**Comment by rudolfgrauberger** [comment]
Erledigt mit https://github.com/Archi-Lab/prox-proposal-service/commit/c3d67fce889645d07792cf2edef915bcfaa8a9b6#diff-c4f7532d328c4f5dded9eb3c64cb466d
