### ISSUE TITLE
Session Rudolf / C. Poloczek, um die Merge-Konventionen (und sonstige Konventionen) zu klären

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-proposal-service#2]

**Comment by rudolfgrauberger** [comment]
Haben am 18.10 von ca. 10 - 15 Uhr zusammen gesessen und folgendes gemacht:
- Mergen von Dev in den eigenen Branch (auch erläutert warum es hilfreich wenn es regelmäßig gemacht wird)
- Pushen der lokalen Änderungen
- Kleinere und häufigere Commits
- Eigene Pipeline/Test-Umgebung erklärt

Da CP lokal noch einige Umstrukturierungen in dem prox-proposal-service machen musste, sollte er es erstmal erledigen. Sobald er damit durch ist, sollte er sich bei mir melden und wir (Julian oder ich) sorgen dafür das die Jenkins/Docker-Dateien für seine Umgebung lauffähig sind. Es ist nicht die Aufgabe des Praxis-Projekts die Jenkinspipeline zu konfigurieren.

**Comment by rudolfgrauberger** [comment]
Aufgaben erledigt
